version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: optica_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: optica_store
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/docker-entrypoint-initdb.d:ro
    networks:
      - optica_network

networks:
  optica_network:
    driver: bridge
